import { describe, expect, it } from 'vitest';
import { MemoryIntelStore } from './infra/memory/intel-store';
import { HumanAssessmentAdapter } from './intel/human-assessment';
import { RadarProblem } from './domain/types';
import { isConfigured, UnconfiguredPort } from './infra/optional-port';
import { MemoryRateAdapters } from './infra/memory/rate';
import { MemoryChainView } from './infra/memory/chain-view';

describe('memory intel store and ports', () => {
  it('covers missing context/repo present-absent and cursor', async () => {
    const s = new MemoryIntelStore();
    await s.ping();
    await s.migrate();
    const repo = await s.upsertGitHubRepository('FederationCoin', 'cpu-miner');
    const ctx = await s.insertScanContext('mill');
    await s.trackRepo(ctx.id, repo.id);
    expect((await s.getTrackedRepo(ctx.id))?.name).toBe('cpu-miner');
    const hourly1 = await s.insertHourlyScanRun();
    const missCtx = await s.upsertMissingScanContextEvent('FederationCoin/other', repo.id);
    await s.observeMissingContext(missCtx, hourly1.id);
    expect(await s.missingContextPresent(missCtx)).toBe(true);
    await s.insertHourlyScanRun();
    expect(await s.missingContextPresent(missCtx)).toBe(false);
    const missOrg = await s.upsertMissingOrgRepoEvent(ctx.id, 'FederationCoin/cpu-miner');
    const hourly2 = await s.insertHourlyScanRun();
    await s.observeMissingRepo(missOrg, hourly2.id);
    expect(await s.missingRepoPresent(missOrg)).toBe(true);
    await s.insertHourlyScanRun();
    expect(await s.missingRepoPresent(missOrg)).toBe(false);
    const page = await s.listPublicEvents();
    expect(page.items.length).toBeGreaterThan(0);
    if (page.cursor) {
      const next = await s.listPublicEvents(page.cursor);
      expect(Array.isArray(next.items)).toBe(true);
    }
    await expect(s.listPublicEvents('%%%')).rejects.toBeInstanceOf(RadarProblem);
    const adapter = new HumanAssessmentAdapter(s);
    const ev = await s.upsertUpstreamMainlineEvent(ctx.id, 'u', 'c', 't');
    await adapter.recordHumanAssessment(ev, 'note');
    await expect(adapter.recordBedrockAssessment(ev, 'n')).rejects.toBeInstanceOf(RadarProblem);
    await expect(adapter.recordCursorAssessment(ev, 'n')).rejects.toBeInstanceOf(RadarProblem);
    expect(isConfigured(new UnconfiguredPort('XPort'))).toBe(false);
    expect(isConfigured(undefined)).toBe(false);
    expect(isConfigured(null)).toBe(false);
    const rates = new MemoryRateAdapters();
    expect((await rates.hitPublicRead('1.1.1.1')).allowed).toBe(true);
    const chain = new MemoryChainView();
    expect((await chain.getTip('testnet')).height).toBe(10);
    await s.ensureMaintainer('tgfcn1qaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa');
    await s.upsertBip({ number: 341, title: 'Taproot', summary: 'a' });
    const again = await s.upsertBip({ number: 341, title: 'Taproot', summary: 'updated' });
    expect(again.summary).toBe('updated');
    await s.followsUpstream(ctx.id, 'u1');
    await s.followsUpstream(ctx.id, 'u1');
    await s.insertRepoObserved(repo.id, hourly1.id, { defaultBranch: 'federationcoin', isPrivate: false });
    await s.upsertPolledFeedSource('x', 'X', 'weekly');
    await s.addEventBucket(missCtx, 'HostedInfraThreat');
    const staleId = await s.upsertStaleUpstreamEvent('up-stale');
    expect((await s.getEvent(staleId))?.type).toBe('StaleUpstreamEvent');
    const bipEv = await s.upsertBipArrivedEvent(again.id);
    expect((await s.getEvent(bipEv))?.type).toBe('BipArrivedEvent');
    await expect(s.ackDistant('m', 'missing')).rejects.toBeInstanceOf(RadarProblem);
    await expect(s.acceptTask('m', 'missing', new Date().toISOString())).rejects.toBeInstanceOf(RadarProblem);
    await expect(s.completeTask('m', 'missing', new Date().toISOString())).rejects.toBeInstanceOf(RadarProblem);
    await expect(s.recordHumanAssessment('missing', 'n')).rejects.toBeInstanceOf(RadarProblem);
    expect(await s.getEvent('nope')).toBeUndefined();
    expect(await s.getScanContext(ctx.id)).toBeTruthy();
    const bipRow = await s.getBip(again.id);
    expect(bipRow?.number).toBe(341);
    expect(await s.listBipIds().then((x) => x.length)).toBeGreaterThan(0);
    expect(await s.listDistantEventIds()).toEqual([]);
    await s.seedQuantumClock({ id: 'c', summary: 'pq', milestones: [] });
    expect((await s.getQuantumClock())?.id).toBe('c');
    const dep = await s.upsertMissingDepScanEvent(ctx.id);
    expect((await s.getEvent(dep))?.type).toBe('MissingDepScanEvent');
    const md = await s.upsertMissingDepScanEvent(ctx.id);
    expect(md).toBe(dep);
  });
});
